<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\Network\Session\DatabaseSession;

/**
 * Categories Controller
 *
 * @property \App\Model\Table\CategoriesTable $Categories
 */
class CategoriesController extends AppController
{
//    public $session;
    public $paginate = [
        'limit' => 1,
//        'order' => [
//            'Articles.title' => 'asc'
//        ]
    ];


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
//        $lstCategory=$this->Categories->getAll();
//        $this->set(compact('lstCategory'));
    }

    public function view($id = null)
    {
        $arr_id=array();
        $session = $this->request->session();
        $article = TableRegistry::get('Articles', [
            'contain' => ['Categories']
        ])->find('all')->where(['cate_id' => $id]);
        $category = $this->Categories->get($id);

//        if($session->check('idcate')==true) {
//            $session->write('idcate', $id);
//            $idss = $session->read('idcate');
//            array_push($arr_id,$idss);
//        }else{
//            $session->write('idcate', $id);
//            $idss = $session->read('idcate');
//            $arr_id[]=$idss;
//        }

        if ($session->check('id')){
            $read=$session->read('id');
            $this->set('read', $read);
        }
        $this->set('categoryId', $id);
        $this->set('category', $category);
        $this->set('article', $this->paginate($article));
        $this->set('_serialize', ['article']);
        $this->set('_serialize', ['category']);

//        echo "<pre>";
//        print_r($category);
//        die;
    }

}
