<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\Network\Session\DatabaseSession;

/**
 * Categories Controller
 *
 * @property \App\Model\Table\CategoriesTable $Categories
 */
class CategoriesController extends AppController
{
    public $id_ses = array();
//    public $session;
    public $paginate = [
        'limit' => 1,
//        'order' => [
//            'Articles.title' => 'asc'
//        ]
    ];

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Paginator');
        $this->session = $this->request->session();
//        $lstCategory=$this->Categories->getAll();
//        $this->set(compact('lstCategory'));
    }

    public function index()
    {
        $this->paginate = [
            'contain' => ['ParentCategories']
        ];
        $categories = $this->paginate($this->Categories);

        $this->set(compact('categories'));
        $this->set('_serialize', ['categories']);
    }

    /**
     * View method
     *
     * @param string|null $id Category id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $arr_id=array();
        $session = $this->request->session();
        $article = TableRegistry::get('Articles', [
            'contain' => ['Categories']
        ])->find('all')->where(['cate_id' => $id]);
        $category = $this->Categories->get($id, [
            'contain' => ['ParentCategories', 'ChildCategories']
        ]);

        if($session->check('idcate')==true) {
            $session->write('idcate', $id);
            $idss = $session->read('idcate');
            array_push($arr_id,$idss);
        }else{
            $session->write('idcate', $id);
            $idss = $session->read('idcate');
            $arr_id[]=$idss;
        }
        if ($session->check('id')){
            $read=$session->read('id');
        }
        $this->set('categoryId', $arr_id);
        $this->set('read', $read);
        $this->set('category', $category);
        $this->set('article', $this->paginate($article));
        $this->set('_serialize', ['article']);
        $this->set('_serialize', ['category']);

//        echo "<pre>";
//        print_r($category);
//        die;
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $category = $this->Categories->newEntity();
        if ($this->request->is('post')) {
            $category = $this->Categories->patchEntity($category, $this->request->data);
            if ($this->Categories->save($category)) {
                $this->Flash->success(__('The category has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The category could not be saved. Please, try again.'));
        }
        $categories = $this->Categories->Categories->find('list', ['limit' => 200]);
        $parentCategories = $this->Categories->ParentCategories->find('list', ['limit' => 200]);
        $this->set(compact('category', 'categories', 'parentCategories'));
        $this->set('_serialize', ['category']);
    }

    public function edit($id = null)
    {
        $category = $this->Categories->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $category = $this->Categories->patchEntity($category, $this->request->data);
            if ($this->Categories->save($category)) {
                $this->Flash->success(__('The category has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The category could not be saved. Please, try again.'));
        }
        $categories = $this->Categories->Categories->find('list', ['limit' => 200]);
        $parentCategories = $this->Categories->ParentCategories->find('list', ['limit' => 200]);
        $this->set(compact('category', 'categories', 'parentCategories'));
        $this->set('_serialize', ['category']);
    }

}
