<?php

namespace App\Controller;

use Cake\Core\Configure;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class HomeController extends AppController
{
    var $helpers=array('Categories');
    public $paginate = [
        'limit' => 1,
//        'order' => [
//            'Articles.title' => 'asc'
//        ]
    ];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->_categorysTbl = TableRegistry::get('categories');
        $category = $this->_categorysTbl->find('all')->where(['parent_id !=' => 0]);
        $this->set('category', $category);

    }

    public function index()
    {

    }

    public function search()
    {
        $this->_articleTbl = TableRegistry::get('articles');
        $article = $this->_articleTbl->find('all');
        if ($this->request->is('post')) {
            $category = $this->request->data('cate_id');
            $articles = $this->request->data('arc_name');
            if ($article == '') {
                $search = $article->where(['cate_id' => $category])->toArray();
            } elseif ($category == 0) {
                $search = $article->where(['arc_name like' => "%$articles%"])
                    ->toArray();
            } else {
                $search = $article->where(['arc_name like' => "%$articles%", 'cate_id' => $category])
                    ->toArray();
            }
            $return=array();
            foreach ($search as $val){
                $return[] = array(
                    'id'=>$val['arc_id'],
                    'name'=>$val['arc_name']
                );
            }
            echo json_encode($return);
            exit();
        }
    }
}

?>