<?php
namespace App\Controller;

use Cake\Core\Configure;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class HomeController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout('default2');
        $this->_articleTbl=TableRegistry::get('articles');
        $this->_categorysTbl=TableRegistry::get('categories');
    }

    public function index()
    {
        $lstCategory=$this->_categorysTbl->getAll();
        $this->set(compact('lstCategory'));
    }
}
?>