<?php
namespace App\Controller;

use Cake\Core\Configure;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class HomeController extends AppController
{
    public $paginate = [
        'limit' => 1,
//        'order' => [
//            'Articles.title' => 'asc'
//        ]
    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->_articleTbl=TableRegistry::get('articles');
        $this->_categorysTbl=TableRegistry::get('categories');
        $category=$this->_categorysTbl->find('all')->where(['parent_id !='=>0]);
        $this->set('category',$category);

    }
//    public function beforeFilter(Event $event)
//    {
//        parent::beforeFilter($event); // TODO: Change the autogenerated stub
//        $lstCategory=$this->_categorysTbl->getAll();
//        $parent=$this->getCategory($lstCategory);
//        $this->set(compact('parent'));
//    }

    public function index()
    {
        $this->_articleTbl=TableRegistry::get('articles');
//        if ($this->request->is('get')){
            $category=$this->request->getQuery('cate_id');
            $article=$this->request->getQuery('arc_name');
            if ($article==''){
                $this->Flash->error(__('Ban hay dien tu khoa tim kiem.'), ['key'=>'auth']);
//                return;
            }
            if ($category==0){
                $search=$this->_articleTbl->find('all')
                    ->where(['arc_name like'=>"%$article"])
                    ->toArray();
            }else{
                $search=$this->_articleTbl->find('all')
                    ->where(['arc_name like'=>"%$article",'cate_id'=>$category])
                    ->toArray();
            }
            $this->set('search',($search));
//        }
    }
}
?>