<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 */
class UsersController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
//    public function beforeFilter(Event $event)
//    {
//        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
//        $this->Auth->allow(['add','logout']);
//    }

    public function login(){
        $this->viewBuilder()->setLayout('login_admin');
        if($this->request->is('post')){
            $user = $this->Auth->identify();
            if($user){
                if ($user['status']==1) {
                    $this->Auth->setUser($user);
                    return $this->redirect($this->Auth->redirectUrl());
                }else{
                    $this->Flash->error(__('Account is not active'),['key'=>'auth']);
                }
            } else
                $this->Flash->error(__('Your username or password is incorrect.'), ['key'=>'auth']);
        }
    }
    public function logout(){
        return $this->redirect($this->Auth->logout());
    }
}
